INSERT INTO mrt_stations (station_name, station_code) VALUES
-- CHANGI AIRPORT SECTION
('Changi Airport', 'CG2'),
('Expo', 'CG1/DT35'),

-- EAST WEST LINE
('Pasir Ris', 'EW1'),
('Tampines', 'EW2'),
('Simei', 'EW3'),
('Tanah Merah', 'EW4/CG'),
('Bedok', 'EW5'),
('Kembangan', 'EW6'),
('Eunos', 'EW7'),
('Paya Lebar', 'EW8/CC9'),
('Aljunied', 'EW9'),
('Kallang', 'EW10'),
('Lavender', 'EW11'),
('Bugis', 'EW12/DT14'),
('Tanjong Pagar', 'EW15'),
('Outram Park', 'EW16/NE3/TE17'),
('Tiong Bahru', 'EW17'),
('Redhill', 'EW18'),
('Queenstown', 'EW19'),
('Commonwealth', 'EW20'),
('Dover', 'EW22'),
('Clementi', 'EW23'),
('Jurong East', 'NS1/EW24'),
('Chinese Garden', 'EW25'),
('Lakeside', 'EW26'),
('Boon Lay', 'EW27'),
('Pioneer', 'EW28'),
('Joo Koon', 'EW29'),
('Gul Circle', 'EW30'),
('Tuas Crescent', 'EW31'),
('Tuas West Road', 'EW32'),
('Tuas Link', 'EW33'),

-- PURPLE LINE
('Chinatown', 'NE4/DT19'),
('Clarke Quay', 'NE5'),
('Little India', 'NE7/DT12'),
('Farrer Park', 'NE8'),
('Boon Keng', 'NE9'),
('Potong Pasir', 'NE10'),
('Woodleigh', 'NE11'),
('Serangoon', 'NE12/CC13'),
('Kovan', 'NE13'),
('Hougang', 'NE14'),
('Buangkok', 'NE15'),
('Sengkang', 'NE16/STC'),
('Punggol', 'NE17/PTC'),
('Punggol Coast', 'NE18'),

-- DOWNTOWN LINE (BLUE)
('Bukit Panjang', 'DT1/BP6'),
('Cashew', 'DT2'),
('Hillview', 'DT3'),
('Hume', 'DT4'),
('Beauty World', 'DT5'),
('King Albert Park', 'DT6'),
('Sixth Avenue', 'DT7'),
('Tan Kah Kee', 'DT8'),
('Stevens', 'DT10/TE11'),
('Rochor', 'DT13'),
('Promenade', 'DT15/CC4'),
('Bayfront', 'DT16/CE1'),
('Downtown', 'DT17'),
('Telok Ayer', 'DT18'),
('Fort Canning', 'DT20'),
('Bencoolen', 'DT21'),
('Jalan Besar', 'DT22'),
('Bendemeer', 'DT23'),
('Geylang Bahru', 'DT24'),
('Mattar', 'DT25'),
('MacPherson', 'DT26/CC10'),
('Ubi', 'DT27'),
('Kaki Bukit', 'DT28'),
('Bedok North', 'DT29'),
('Bedok Reservoir', 'DT30'),
('Tampines West', 'DT31'),
('Tampines East', 'DT33'),
('Upper Changi', 'DT34'),
('Xilin', 'DT36'),

-- CIRCLE LINE (YELLOW)
('Bras Basah', 'CC2'),
('Esplanade', 'CC3'),
('Nicoll Highway', 'CC5'),
('Stadium', 'CC6'),
('Mountbatten', 'CC7'),
('Dakota', 'CC8'),
('Tai Seng', 'CC11'),
('Bartley', 'CC12'),
('Lorong Chuan', 'CC14'),
('Marymount', 'CC16'),
('Caldecott', 'CC17/TE9'),
('Botanic Gardens', 'CC19/DT9'),
('Farrer Road', 'CC20'),
('Holland Village', 'CC21'),
('Buona Vista', 'CC22/EW21'),
('one-north', 'CC23'),
('Kent Ridge', 'CC24'),
('Haw Par Villa', 'CC25'),
('Pasir Panjang', 'CC26'),
('Labrador Park', 'CC27'),
('Telok Blangah', 'CC28'),
('HarbourFront', 'CC29/NE1'),

-- NORTH–SOUTH LINE (RED)
('Bukit Batok', 'NS2'),
('Bukit Gombak', 'NS3'),
('Choa Chu Kang', 'NS4/BP1'),
('Yew Tee', 'NS5'),
('Kranji', 'NS7'),
('Marsiling', 'NS8'),
('Woodlands', 'NS9/TE2'),
('Admiralty', 'NS10'),
('Sembawang', 'NS11'),
('Canberra', 'NS12'),
('Yishun', 'NS13'),
('Khatib', 'NS14'),
('Yio Chu Kang', 'NS15'),
('Ang Mo Kio', 'NS16'),
('Bishan', 'NS17/CC15'),
('Braddell', 'NS18'),
('Toa Payoh', 'NS19'),
('Novena', 'NS20'),
('Newton', 'NS21/DT11'),
('Somerset', 'NS23'),
('Dhoby Ghaut', 'NS24/NE6/CC1'),
('City Hall', 'NS25/EW13'),
('Raffles Place', 'NS26/EW14'),
('Marina Bay', 'NS27/TE20/CE2'),
('Marina South Pier', 'NS28'),

-- THOMSON–EAST COAST LINE (BROWN)
('Woodlands North', 'TE1'),
('Woodlands South', 'TE3'),
('Springleaf', 'TE4'),
('Lentor', 'TE5'),
('Mayflower', 'TE6'),
('Bright Hill', 'TE7'),
('Upper Thomson', 'TE8'),
('Napier', 'TE12'),
('Orchard Boulevard', 'TE13'),
('Orchard', 'TE14/NS22'),
('Great World', 'TE15'),
('Havelock', 'TE16'),
('Maxwell', 'TE18'),
('Shenton Way', 'TE19'),
('Gardens by the Bay', 'TE22'),
('Tanjong Rhu', 'TE23'),
('Katong Park', 'TE24'),
('Tanjong Katong', 'TE25'),
('Marine Parade', 'TE26'),
('Marine Terrace', 'TE27'),
('Siglap', 'TE28'),
('Bayshore', 'TE29'),
('Bedok South', 'TE30'),
('Sungei Bedok', 'TE31/DT37'),

-- BUKIT PANJANG LRT (BP)
('South View', 'BP2'),
('Keat Hong', 'BP3'),
('Teck Whye', 'BP4'),
('Phoenix', 'BP5'),
('Petir', 'BP7'),
('Pending', 'BP8'),
('Bangkit', 'BP9'),
('Fajar', 'BP10'),
('Segar', 'BP11'),
('Jelapang', 'BP12'),
('Senja', 'BP13'),

-- SENGKANG LRT (SK)
('Compassvale', 'SE1'),
('Rumbia', 'SE2'),
('Bakau', 'SE3'),
('Kangkar', 'SE4'),
('Ranggung', 'SE5'),
('Cheng Lim', 'SW1'),
('Farmway', 'SW2'),
('Kupang', 'SW3'),
('Thanggam', 'SW4'),
('Fernvale', 'SW5'),
('Layar', 'SW6'),
('Tongkang', 'SW7'),
('Renjong', 'SW8'),

-- PUNGGOL LRT (PG)
('Cove', 'PE1'),
('Meridian', 'PE2'),
('Coral Edge', 'PE3'),
('Riviera', 'PE4'),
('Kadaloor', 'PE5'),
('Oasis', 'PE6'),
('Damai', 'PE7'),
('Sam Kee', 'PW1'),
('Teck Lee', 'PW2'),
('Punggol Point', 'PW3'),
('Samudera', 'PW4'),
('Nibong', 'PW5'),
('Sumang', 'PW6'),
('Soo Teck', 'PW7');
